services:
  - type: web
    name: biofitiq-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uv run uvicorn main:app --host 0.0.0.0 --port 10000"
    autoDeploy: true
